🔧 cronjobs optimizations

diff --git a/cluster/apps/downloaders/qbittorrent-jobs/cron-job.yaml b/cluster/apps/downloaders/qbittorrent-jobs/cron-job.yaml
--- a/cluster/apps/downloaders/qbittorrent-jobs/cron-job.yaml
+++ b/cluster/apps/downloaders/qbittorrent-jobs/cron-job.yaml
@@ -23,15 +23,19 @@ spec:
                 - |
                   #!/bin/bash
 
-                  set -o nounset
                   set -o errexit
+                  set -o nounset
 
                   curl --location https://github.com/DavidMoore/ipfilter/releases/download/lists/ipfilter.dat.gz --output /tmp/ipfilter.dat.gz
                   gunzip /tmp/ipfilter.dat.gz
                   result=$(kubectl get pod --selector app.kubernetes.io/name=qbittorrent --output custom-columns=:metadata.name --namespace default)
                   QBITTORRENT_POD=$(echo $result | awk '{ print $NF }')
                   echo $QBITTORRENT_POD | grep qbittorrent
-                  test $? -eq 0 && kubectl cp /tmp/ipfilter.dat default/$QBITTORRENT_POD:/config/ipfilter.dat
-                  curl -m 10 --retry 5 http://healthchecks.default.svc.cluster.local.:/ping/{ping_key}/k3s-qbittorrent-p2pblocklist
-                  kubectl rollout restart deployment qbittorrent --namespace default
+                  if [[ $(echo $QBITTORRENT_POD | grep qbittorrent) ]]; then
+                    kubectl cp /tmp/ipfilter.dat default/$QBITTORRENT_POD:/config/ipfilter.dat
+                    kubectl rollout restart deployment qbittorrent --namespace default && curl -m 10 --retry 5 http://healthchecks.default.svc.cluster.local.:/ping/${SECRET_HEALTHCHECKS_PING_KEY}/k3s-qbittorrent-p2pblocklist
+                  else
+                    echo "qbittorrent deployment not found"
+                    exit 1
+                  fi
           restartPolicy: Never
